stages:
  - deploy

deploy:
  stage: deploy
  tags: 
    - docker
    - ots
  script:
    - cp ${CI_SERVER_TLS_CA_FILE} /usr/local/share/ca-certificates/gitlab-ca.crt
    - /usr/sbin/update-ca-certificates
    - cd src/RabbitRpc.Core
    - dotnet pack -c Release
    - dotnet nuget add source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet nuget push "bin/Release/*.nupkg" --source gitlab
  only:
    - master
  environment: production